In [2]:
pip install pdfplumber


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 889.4 kB/s eta 0:00:0036m0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 5.9 MB/s eta 0:00:000:00:010:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 5.6 MB/s eta 0:00:00m eta 0:00:010:01:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pdfplumber

def pdf_to_string(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        text = ''
        for page in pdf.pages:
            text += page.extract_text()
    return text

# Example usage
pdf_path_adarsh = 'Adarsh Mishra-resume.pdf'
pdf_adarsh = pdf_to_string(pdf_path_adarsh)
pdf_path_aryan = 'Aryan Kaushik Resume.pdf'
pdf_aryan= pdf_to_string(pdf_path_aryan)
pdf_path_abhi='Abhishek Verma (1).pdf'
pdf_abhi=pdf_to_string(pdf_path_abhi)
pdf_path_alok='resume_ARD (1).pdf'
pdf_alok=pdf_to_string(pdf_path_alok)
pdf_path_aditya='aditya_3.1.pdf'
pdf_aditya=pdf_to_string(pdf_path_aditya)
pdf_path_ayush='ayush.pdf'
pdf_ayush=pdf_to_string(pdf_path_ayush)
print(pdf_aditya)


ADITYA KUMAR
Delhi, India | +917903113366 | adityapanday7903@gmail.com | www.linkedin.com/in/adityakumarpandey/
EDUCATION
KIET Group of Institutions – Ghaziabad, Delhi NCR 2021-2025
Bachelor of Technology, Information Technology.
BD Public School – Vaishali, Bihar 2018-2020
Intermediate with Maths, Physics, Chemistry
EXPERIENCE
CISCO
Cyber Security Intern May 2023 – August 2023
• Developed a comprehensive foundation in cloud security, Linux systems, cybersecurity essentials, and networking.
• Implemented security protocols and configurations on Linux servers, enhancing system protection by 20%.
Campus Internship KIET
DSA and C/C++ Aug 2022 – Oct 2022
• Acquired networking skills and integrated workplace culture practices.
• Developed a game using basic C programming utilized by 10+ students.
CERTIFICATIONS
Introduction to Machine learning with R (Jul 2022) Cybersecurity Essentials (Aug 2023)
Programming Essentials in C++ (Dec 2022) Cloud Security Training (Dec 2023)
CCNA Introduction t

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


In [3]:
file=pd.read_csv('resu.csv',nrows=891)

In [4]:
file

Category                                             Resume
0           1  Skills * Programming Languages: Python (pandas...
1           1  Education Details _x000D_\nMay 2013 to May 201...
2           1  Areas of Interest Deep Learning, Control Syste...
3           1  Skills • R • Python • SAP HANA ...
4           1  Education Details _x000D_\n MCA   YMCAUST,  Fa...
..        ...                                                ...
886        24  SKILLS Bitcoin, Ethereum Solidity Hyperledger,...
887        24  Hobbies • Playing Chess • Solving Ru...
888        24  Skills Strong CS fundamentals and problem solv...
889        24  KEY SKILLS: Programing languages: C, C++, Pyth...
890        24  SOFTWARE SKILLS: Languages: C, C++ & java Oper...

[891 rows x 2 columns]

In [5]:
classy=file[['Category']]
classx=file[['Resume']]
print(classx)
print(classy)

                                                Resume
0    Skills * Programming Languages: Python (pandas...
1    Education Details _x000D_\nMay 2013 to May 201...
2    Areas of Interest Deep Learning, Control Syste...
3    Skills • R • Python • SAP HANA ...
4    Education Details _x000D_\n MCA   YMCAUST,  Fa...
..                                                 ...
886  SKILLS Bitcoin, Ethereum Solidity Hyperledger,...
887  Hobbies • Playing Chess • Solving Ru...
888  Skills Strong CS fundamentals and problem solv...
889  KEY SKILLS: Programing languages: C, C++, Pyth...
890  SOFTWARE SKILLS: Languages: C, C++ & java Oper...

[891 rows x 1 columns]
     Category
0           1
1           1
2           1
3           1
4           1
..        ...
886        24
887        24
888        24
889        24
890        24

[891 rows x 1 columns]


In [6]:
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
ps = WordNetLemmatizer()
c = []
for i in range(0, len(classx)):
    r=re.sub('[^a-zA-Z]', ' ',classx['Resume'][i])
    r=r.lower()
    r=r.split()

    r=[ps.lemmatize(word) for word in r if not word in stopwords.words('english')]
    r=' '.join(r)
    c.append(r)

c

[nltk_data] Downloading package stopwords to /home/alok-ranjan-
[nltk_data]     dubey/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/alok-ranjan-
[nltk_data]     dubey/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


['skill programming language python panda numpy scipy scikit learn matplotlib sql java javascript jquery machine learning regression svm na bayes knn random forest decision tree boosting technique cluster analysis word embedding sentiment analysis natural language processing dimensionality reduction topic modelling lda nmf pca neural net database visualization mysql sqlserver cassandra hbase elasticsearch j dc j plotly kibana matplotlib ggplot tableau others regular expression html cs angular logstash kafka python flask git docker computer vision open cv understanding deep learning education detail x x data science assurance associate x x data science assurance associate ernst young llp x skill detail x javascript exprience month x jquery exprience month x python exprience monthscompany detail x company ernst young llp x description fraud investigation dispute service assurance x technology assisted review x tar technology assisted review assist accelerating review process run analytic

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
classx = cv.fit_transform(c).toarray()
print(classx)
type(classx)
print(classy)
type(classy)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
     Category
0           1
1           1
2           1
3           1
4           1
..        ...
886        24
887        24
888        24
889        24
890        24

[891 rows x 1 columns]


pandas.core.frame.DataFrame

In [8]:
from sklearn.model_selection import train_test_split
xclass_t, xclass_test, yclass_t, yclass_test = train_test_split(classx, classy,test_size = 0.3, random_state =1)
xclass_train, xclass_val, yclass_train, yclass_val = train_test_split(xclass_t, yclass_t, test_size = 0.2,random_state = 2)
xclass_train.shape

(498, 6256)

In [9]:
from sklearn.naive_bayes import MultinomialNB
f= MultinomialNB().fit(xclass_train, yclass_train)

/home/alok-ranjan-dubey/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
q=pd.read_csv("resu.csv",nrows=1100)
q=q.iloc[892:961]
q

Category                                             Resume
892  Testing  • Good logical and analytical skills â€...
893  Testing  COMPUTER PROFICIENCY • Basic: MS-Office (...
894  Testing  Computer Skills: • Proficient in MS offic...
895  Testing  ❖ Willingness to accept the challenges. Ã...
896  Testing  PERSONAL SKILLS • Quick learner, • E...
..       ...                                                ...
956  Testing  COMPUTER PROFICIENCY • Basic: MS-Office (...
957  Testing  Computer Skills: • Proficient in MS offic...
958  Testing  ❖ Willingness to accept the challenges. Ã...
959  Testing  PERSONAL SKILLS • Quick learner, • E...
960  Testing  COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...

[69 rows x 2 columns]

In [11]:
q = pd.read_csv("resu.csv", nrows=1100)
q = q.iloc[792:861]
classX = q['Resume'].values
classY = q['Category'].astype(int).values

r = []
for i in range(len(classX)):
    p = re.sub('[^a-zA-Z]', ' ', classX[i])
    p = p.lower()
    p = p.split()
    p = [ps.lemmatize(word) for word in p if not word in stopwords.words('english')]
    p = ' '.join(p)
    r.append(p)

z = cv.transform(r).toarray()
print(classY)
print(classX)
y_pred_new = f.predict(z)
print(y_pred_new)

[22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22
 22 22 22 22 22 22 22 22 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23
 23 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24]
['SKILL SET ✓ Talend Big Data ✓ Informatica Power center ✓ Microsoft SQL Server ✓ SQL Platform 6.2.1 Management Studio Workbench ✓ AWS Services ✓ Talend Administration Console ✓ Microsoft Visual ✓ Redshift (TAC) Studio ✓ Athena ✓ Data Warehouse Concept - Star ✓ SQL ✓ S3 Schema, Facts, Dimensions ✓ Data Modeling - ✓ Data Integration Microsoft Access Education Details _x000D_\nJanuary 2012 to January 2016 BE  Mumbai, Maharashtra University of Mumbai_x000D_\nJanuary 2012 CBSE Technology Kochi, Kerala St. Francis_x000D_\nTalend ETL Developer _x000D_\n_x000D_\nTalend ETL Developer - Tata Consultancy Services_x000D_\nSkill Details _x000D_\nDATA WAREHOUSE- Exprience - 23 months_x000D_\nDATABASE- Exprience - 20 months

In [12]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(classY, y_pred_new)
print(f'Accuracy: {accuracy}')

Accuracy: 0.8840579710144928


In [13]:
q=pd.read_csv("resu.csv",nrows=1100)
q=q.iloc[892:961]
q
classX=q['Resume'][896]

classX

"PERSONAL SKILLS • Quick learner, • Eagerness to learn new things, • Competitive attitude, • Good leadership qualities, • Ability to deal with people diplomatically. PERSONAL DOSSIER Fathers Name: Dhanraj WaghEducation Details _x000D_\nJanuary 2012 to January 2016 Bachelors of Engineering Engineering Pune, Maharashtra Pune University_x000D_\nJanuary 2012 Higher Secondary Certificate  Nashik, Maharashtra SND College of Engineering and Research Center_x000D_\nJanuary 2010 Secondary School Certificate  Yeola, Maharashtra Swami Muktanand Jr. College_x000D_\n HSC   Maharashtra State Board_x000D_\n SSC   Maharashtra State Bard_x000D_\n BE  Rajapur, Uttar Pradesh Madhyamik Vidya Mandir Rajapur_x000D_\nTesting and Quality Control Engineer _x000D_\n_x000D_\nTesting and Quality Control Engineer - M/S Rakesh Transformer Industries Pvt. Ltd_x000D_\nSkill Details _x000D_\nCompany Details _x000D_\ncompany - M/S Rakesh Transformer Industries Pvt. Ltd_x000D_\ndescription - Res

In [14]:
s='''An Undergrad Engineering student looking for experience in Field of Software development.
EDUCATION
Bachelor of Computer Science, KIET Group Of Institutions
CGPA: 8.7511 - 2025
Intermediate School, K.V Ranikhet
CBSE Boards: 962019 - 2020
SKILLS
Technical Skills
Soft Skills
Languages
DSA, JavaScript, ReactJS, NodeJS, NextJS, ExpressJS, GIT, Linux, MongoDB
Poise, Diplomacy, Cultural intelligence, Vision, Self-Awareness
English, Hindi
EXPERIENCE
Summer Intern
YBI Foundations
August 2022 - November 2022
Noida, Uttar Pradesh
• Skilled in data engineering, machine learning, and data classification, with experience using regression, classifi-
cation, and neural network models.
• Developed machine learning projects, including a highly accurate (87%) iris classification model and a disease
prediction model..
PROJECTS
Sonara. Developed a full-stack music player using Next.js and Supabase database, enabling users to manage their
music library, create playlists, and listen to songs(100+) on demand.(Try it here)
Personalized Portfolio Interactive Next.js portfolio with a modern UI and user-friendly design, highlighting my
skills, experience, and projects(5+), with easy-to-use contact information.(Try it here)
Amazon Clone Built and deployed an Amazon clone with an identical UI, cart for marked products (up to 100
items), checkout page with completely working payment options (99% success rate), using React.js, Firebase.js, and
Stripe (5,000 lines of code written, 2 weeks to build and deploy).(Try it here)
COURSES
• Complete Web development BootCamp It is a 66 hours course that taught about Web Development and Version
control along with projects like to-do list and Notes website. (Credential)
April 2023
• Machine Learning Specialization A 6 Months Long Course that covered most important topics in Machine
learning and taught about supervised learning, Unsupervised learning, Reinforced learning and neural net-
works.Credential
ACHIEVEMENTS
• Co-Ordinator at a Technical Club DevUp in our University for 1+ year.
• 250+ Questions on LeetCode.
• 3 Star in CodeChef
• 2 hackathons Finalist.'''
r=[]
p=re.sub('[^a-zA-Z]', ' ',s)
#p=re.sub('[^a-zA-Z]', ' ',classX)
#p=re.sub('[^a-zA-Z]', ' ',pdf_abhi)
#p=re.sub('[^a-zA-Z]', ' ',pdf_aryan)
#p=re.sub('[^a-zA-Z]', ' ',pdf_adarsh)
#p=re.sub('[^a-zA-Z]', ' ',pdf_alok)
#p=re.sub('[^a-zA-Z]', ' ',pdf_aditya)
#p=re.sub('[^a-zA-Z]', ' ',pdf_ayush)
p = p.lower()
p = p.split()
p = [ps.lemmatize(word) for word in p if not word in stopwords.words('english')]
p = ' '.join(p)
r.append(p)
z=cv.transform(r).toarray()

In [15]:
y_pred_2=f.predict(z)

In [16]:
if y_pred_2==1:
    print("Data Science Engineer")
if y_pred_2==2:
    print("HR")
if y_pred_2==3:
    print("Advocate")
if y_pred_2==4:
    print("Arts")
if y_pred_2==5:
    print("Web D")
if y_pred_2==6:
    print("Mechanical Engineer")
if y_pred_2==7:
    print("Sales")
if y_pred_2==8:
    print("Health And Fitness")
if y_pred_2==9:
    print("Civil")
if y_pred_2==10:
    print("Java")
if y_pred_2==11:
    print("Business Analyst")
if y_pred_2==12:
    print("SAP")
if y_pred_2==14:
    print("Electrical Engineer")

Data Science Engineer


In [17]:
y_pred_2

array([1])

In [18]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(f, file)


In [19]:
pip install streamlit


Note: you may need to restart the kernel to use updated packages.


In [20]:
%%writefile app.py

import streamlit as st
import pickle
import numpy as np

# Load your trained model
with open('model.pkl', 'rb') as file:
    model = pickle.load(file)

# Define a function to make predictions
def predict_category(text):
    prediction = model.predict([text])
    return prediction[0]

# Streamlit app interface
st.title("Resume Category Predictor")

# Input text box
text_input = st.text_area("Enter the resume text here:")

# Predict button
if st.button("Predict"):
    if text_input:
        category = predict_category(text_input)
        st.write(f"The predicted category is: **{category}**")
    else:
        st.write("Please enter some text.")


Overwriting app.py


In [314]:
!streamlit run app.py


Traceback (most recent call last):
  File "/home/alok-ranjan-dubey/anaconda3/bin/streamlit", line 7, in <module>
    from streamlit.cli import main
ModuleNotFoundError: No module named 'streamlit.cli'


In [21]:
conda init /home/alok-ranjan-dubey/anaconda3/bin/python


usage: conda init [-h] [--all] [--user] [--no-user] [--system] [--reverse]
                  [--json] [-v] [-q] [-d]
                  [SHELLS ...]
conda init: error: argument SHELLS: invalid choice: '/home/alok-ranjan-dubey/anaconda3/bin/python' (choose from 'bash', 'fish', 'tcsh', 'xonsh', 'zsh', 'powershell')

Note: you may need to restart the kernel to use updated packages.


In [315]:
import sys
print(sys.executable)


/home/alok-ranjan-dubey/anaconda3/bin/python
